name: CI

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened] 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "12.x"

      - name: Run NPM CI
        run: npm ci

      - name: Check Code Formatting
        run: npm run format:check
      
      - name: Run Automated Tests
        run: npm test -- --coverage
        env:
          CI: true
